# Generated by Django 4.1.1 on 2023-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
