# Generated by Django 4.1.1 on 2023-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_complaint_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
